version: '3.4'
services:
# додаток
  app:
    image: php:8.0-apache
    build:
      context: .
      dockerfile: PhpApache.Dockerfile
    ports:
      - 80:80                                                       # прокинути порт веб-серверу
    volumes:  
      - ./test:/var/www                                               # прокинути папку з файлами веб-сайту
      - ./test.conf:/etc/apache2/sites-available/000-default.conf     # прокинути конфігурацію веб-серверу
# СУБД
  db:
    image: mysql:latest
    build:
      context: .
      dockerfile: Mysql.Dockerfile
    environment: 
      - MYSQL_DATABASE=laravel                                        # БД
      - MYSQL_USER=laravel_user                                       # Кристувач
      - MYSQL_PASSWORD=P@ssw0rd                                       # Пароль користувача
# Для створення БД. 
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    ports:
      - 3306:3306                         # треба прокинути порт 3606 для БД.
  redis:
    image: redis:latest
    ports: 
      - 6379:6379